const defaultShowcaseClips = {
  success: 1,
  data: [
    {
      id: "192043",
      campaign_id: "9000",
      tv_entity_type_id: "24",
      root_tv_entity_id: "192042",
      parent_tv_entity_id: "192042",
      is_topic: "0",
      teaser_video_asset_id: null,
      video_asset_id: "143922",
      broadcast_id: null,
      active_media_type: "video",
      label: "PG Showcase Benefits",
      slug: "pg-showcases",
      slug_aliases: "",
      external_content_id: null,
      external_content_type: null,
      description: "PG - Where the Pros Play",
      poster_image_url:
        "//web-cdn.perfectgame.tv/tv/9000/24/192043_poster_0029.jpg",
      poster_thumbnail_url:
        "//web-cdn.perfectgame.tv/tv/9000/24/192043_poster_0029.jpg",
      vertical_image_url: null,
      vertical_thumbnail_url: null,
      background_image_url: null,
      start_availability_date: null,
      end_availability_date: null,
      actual_start_time: null,
      actual_end_time: null,
      media_create_date: null,
      is_active: "1",
      tv_ad_profile_id: null,
      display_order: "100",
      cache_time: "300",
      is_link: null,
      link_location: null,
      scheduled_build_timestamp: null,
      schedule_build_queued: null,
      last_build_timestamp: "2022-08-15 16:30:13",
      create_user_id: "40",
      update_user_id: "40",
      published_timestamp: "2020-04-14 20:07:27",
      rights_status: "2",
      rights_run_timestamp: null,
      rights_update_timestamp: null,
      rights_notes: null,
      rights_change_notes: null,
      create_timestamp: "2020-04-14 19:54:10",
      update_timestamp: "2020-04-30 19:31:53",
      entity_identifier: "009000-192043",
      parent_label: "PG Promotional",
      parent_link: "23/192042/video-collection/pg-promotional",
      root_label: "PG Promotional",
      root_slug: "pg-promotional",
      root_link: "23/192042/video-collection/pg-promotional",
      root_type_name: "Video Collection",
      root_type_name_plural: "Video Collections",
      type_name: "Video Collection Video",
      is_video_wrapper: "1",
      link: "24/192043/video-1/pg-showcases",
      actual_time_formatted: "",
      actual_time_simple: "",
      actual_date_simple: "",
      published_date: "Apr 14, 2020",
      start_availability_unix: 0,
      end_availability_unix: 0,
      actual_start_unix: 0,
      actual_end_unix: 0,
      video_playlist_url:
        "video.perfectgame.tv/009000-143922-pg_076u/hls/desktop-playlist.m3u8",
      video_mobile_playlist_url:
        "video.perfectgame.tv/009000-143922-pg_076u/hls/mobile-playlist.m3u8",
      video_provisioned: "1",
      duration: "123",
      video_duration_simple_format: "2 min",
      video_duration_time_format: "2:03",
      close_caption_path:
        "//video.perfectgame.tv/009000-143922-pg_076u/cc/cc.vtt",
      active_playlist_url:
        "video.perfectgame.tv/009000-143922-pg_076u/hls/desktop-playlist.m3u8",
      active_mobile_playlist_url:
        "video.perfectgame.tv/009000-143922-pg_076u/hls/mobile-playlist.m3u8",
    },
    {
      id: "192044",
      campaign_id: "9000",
      tv_entity_type_id: "24",
      root_tv_entity_id: "192042",
      parent_tv_entity_id: "192042",
      is_topic: "0",
      teaser_video_asset_id: null,
      video_asset_id: "143923",
      broadcast_id: null,
      active_media_type: "video",
      label: "Introducing PerfectGame.tv",
      slug: "introducing-perfectgametv-1",
      slug_aliases: "",
      external_content_id: null,
      external_content_type: null,
      description: "Introducing PerfectGame.tv",
      poster_image_url:
        "//web-cdn.perfectgame.tv/tv/9000/24/192044_poster_0001.jpg",
      poster_thumbnail_url:
        "//web-cdn.perfectgame.tv/tv/9000/24/192044_poster_0001.jpg",
      vertical_image_url: null,
      vertical_thumbnail_url: null,
      background_image_url: null,
      start_availability_date: null,
      end_availability_date: null,
      actual_start_time: null,
      actual_end_time: null,
      media_create_date: null,
      is_active: "1",
      tv_ad_profile_id: null,
      display_order: "100",
      cache_time: "300",
      is_link: null,
      link_location: null,
      scheduled_build_timestamp: null,
      schedule_build_queued: null,
      last_build_timestamp: "2022-08-15 16:30:08",
      create_user_id: "40",
      update_user_id: "40",
      published_timestamp: "2020-04-22 20:38:50",
      rights_status: "2",
      rights_run_timestamp: null,
      rights_update_timestamp: null,
      rights_notes: null,
      rights_change_notes: null,
      create_timestamp: "2020-04-22 20:21:25",
      update_timestamp: "2020-04-30 19:31:56",
      entity_identifier: "009000-192044",
      parent_label: "PG Promotional",
      parent_link: "23/192042/video-collection/pg-promotional",
      root_label: "PG Promotional",
      root_slug: "pg-promotional",
      root_link: "23/192042/video-collection/pg-promotional",
      root_type_name: "Video Collection",
      root_type_name_plural: "Video Collections",
      type_name: "Video Collection Video",
      is_video_wrapper: "1",
      link: "24/192044/video-1/introducing-perfectgametv-1",
      actual_time_formatted: "",
      actual_time_simple: "",
      actual_date_simple: "",
      published_date: "Apr 22, 2020",
      start_availability_unix: 0,
      end_availability_unix: 0,
      actual_start_unix: 0,
      actual_end_unix: 0,
      video_playlist_url:
        "video.perfectgame.tv/009000-143923-pg_a8yh/hls/desktop-playlist.m3u8",
      video_mobile_playlist_url:
        "video.perfectgame.tv/009000-143923-pg_a8yh/hls/mobile-playlist.m3u8",
      video_provisioned: "1",
      duration: "30",
      video_duration_simple_format: "30 sec",
      video_duration_time_format: "0:30",
      close_caption_path:
        "//video.perfectgame.tv/009000-143923-pg_a8yh/cc/cc.vtt",
      active_playlist_url:
        "video.perfectgame.tv/009000-143923-pg_a8yh/hls/desktop-playlist.m3u8",
      active_mobile_playlist_url:
        "video.perfectgame.tv/009000-143923-pg_a8yh/hls/mobile-playlist.m3u8",
    },
    {
      id: "286409",
      campaign_id: "9000",
      tv_entity_type_id: "24",
      root_tv_entity_id: "192042",
      parent_tv_entity_id: "192042",
      is_topic: "0",
      teaser_video_asset_id: null,
      video_asset_id: "335515",
      broadcast_id: null,
      active_media_type: "video",
      label: "We Are Perfect Game ",
      slug: "we-are-perfect-game-",
      slug_aliases: null,
      external_content_id: null,
      external_content_type: null,
      description:
        "A brief look at the history of Perfect Game and it's effort to grow the game and its players.",
      poster_image_url:
        "//web-cdn.perfectgame.tv/tv/9000/24/286409_poster_we-are-perfect-game-poster773471",
      poster_thumbnail_url:
        "//web-cdn.perfectgame.tv/tv/9000/24/286409_poster_we-are-perfect-game-poster773471",
      vertical_image_url: null,
      vertical_thumbnail_url: null,
      background_image_url: null,
      start_availability_date: null,
      end_availability_date: null,
      actual_start_time: "2020-06-08 11:37:00",
      actual_end_time: "2020-06-08 11:37:00",
      media_create_date: null,
      is_active: "1",
      tv_ad_profile_id: null,
      display_order: "100",
      cache_time: "300",
      is_link: "0",
      link_location: null,
      scheduled_build_timestamp: null,
      schedule_build_queued: null,
      last_build_timestamp: "2022-06-24 13:35:02",
      create_user_id: "98",
      update_user_id: "98",
      published_timestamp: "2022-06-24 13:34:30",
      rights_status: "2",
      rights_run_timestamp: null,
      rights_update_timestamp: null,
      rights_notes: null,
      rights_change_notes: null,
      create_timestamp: "2020-06-08 11:25:33",
      update_timestamp: "2022-06-24 13:34:30",
      entity_identifier: "009000-286409",
      parent_label: "PG Promotional",
      parent_link: "23/192042/video-collection/pg-promotional",
      root_label: "PG Promotional",
      root_slug: "pg-promotional",
      root_link: "23/192042/video-collection/pg-promotional",
      root_type_name: "Video Collection",
      root_type_name_plural: "Video Collections",
      type_name: "Video Collection Video",
      is_video_wrapper: "1",
      link: "24/286409/video-1/we-are-perfect-game-",
      actual_time_formatted: "June 8th, 11:37am ET to 11:37am ET",
      actual_time_simple: "Jun 8, 11:37am ET",
      actual_date_simple: "Jun 8",
      published_date: "Jun 24, 2022",
      start_availability_unix: 0,
      end_availability_unix: 0,
      actual_start_unix: 1591630620,
      actual_end_unix: 1591630620,
      video_playlist_url:
        "video.perfectgame.tv/009000-335515-pg-321_5ls6/hls/desktop-playlist.m3u8",
      video_mobile_playlist_url:
        "video.perfectgame.tv/009000-335515-pg-321_5ls6/hls/mobile-playlist.m3u8",
      video_provisioned: "1",
      duration: "223",
      video_duration_simple_format: "4 min",
      video_duration_time_format: "3:43",
      close_caption_path: "",
      active_playlist_url:
        "video.perfectgame.tv/009000-335515-pg-321_5ls6/hls/desktop-playlist.m3u8",
      active_mobile_playlist_url:
        "video.perfectgame.tv/009000-335515-pg-321_5ls6/hls/mobile-playlist.m3u8",
    },
  ],
  errors: [],
  count: 3,
  params: {
    campaign: "9000",
    topics: ["playerid-357753"],
    url: "https://www.perfectgame.org/Players/Playerprofile.aspx?ID=357753",
    domain: "",
  },
};

export default defaultShowcaseClips;
